import {
  BBQChickenMacon,
  BBQChickenSuya,
  BBQMeatLovers,
  ChickenSupreme,
  ChocolatePizza,
  DoubleCheese,
  HutChilliChicken,
  HutChilliMeat,
  HutChilliVeg,
  Margherita,
  Pepperoni,
  PeriPeriChicken,
  PeriPeriVeg,
  SuperSupreme,
  SweetChilliChicken,
  TikkaChicken,
  TikkaVeg,
  TripleMeatSuya,
} from "../assets";

export const PIZZA = [
  {
    id: 1,
    productName: "BBQ Chicken and Macon",
    productDescription: "BBQ Sauce, Chicken, Diced Macon",
    productPrice: 8100,
    productImage: BBQChickenMacon,
  },

  {
    id: 2,
    productName: "BBQ Chicken and Suya",
    productDescription: "BBQ Sauce, Chicken suya, Red Onion and Green Pepper",
    productPrice: 7600,
    productImage: BBQChickenSuya,
  },
  {
    id: 3,
    productName: "BBQ Meat Lovers",
    productDescription: "BBQ Sauce, Pepperoni, Beef, Sliced Macon, Diced Macon",
    productPrice: 8100,
    productImage: BBQMeatLovers,
  },

  {
    id: 4,
    productName: "Chicken Supreme",
    productDescription:
      "Pizza Sauce, pepperoni, Sliced macon,Beef, diced macon,veggie mix, olives, macon",
    productPrice: 7600,
    productImage: ChickenSupreme,
  },
  {
    id: 5,
    productName: "CHOCOLATE PIZZA",
    productDescription: "Chocolate Pizza",
    productPrice: 2600,
    productImage: ChocolatePizza,
  },
  {
    id: 6,
    productName: "DOUBLE CHEESE",
    productDescription: "Pizza sauce and Mozarella",
    productPrice: 7600,
    productImage: DoubleCheese,
  },
  {
    id: 7,
    productName: "Hut Chilli Chicken",
    productDescription:
      "Sweet chilli sauce, chicken, pepperdew, red onion, green pepper,sweet corn",
    productPrice: 7600,
    productImage: HutChilliChicken,
  },
  {
    id: 10,
    productName: "Hut Chilli Meat",
    productDescription: "Beef, BBQ Sauce, Red Onions, Green Pepper, pepperdew",
    productPrice: 8100,
    productImage: HutChilliMeat,
  },
  {
    id: 11,
    productName: "Hut Chilli Veg",
    productDescription: "BBQ sauce, Veggie mix, Pepperdew, black olives",
    productPrice: 7400,
    productImage: HutChilliVeg,
  },
  {
    id: 12,
    productName: "Margheritae",
    productDescription: "Pizza Sauce and Mozarella",
    productPrice: 7000,
    productImage: Margherita,
  },
  {
    id: 13,
    productName: "Pepperoni",
    productDescription: "Pepperoni and Mozarella",
    productPrice: 8100,
    productImage: Pepperoni,
  },
  {
    id: 14,
    productName: "Peri Peri Chicken",
    productDescription: "Chicken, Peri-Peri Sauce and Jalapenos",
    productPrice: 7600,
    productImage: PeriPeriChicken,
  },
  {
    id: 15,
    productName: "Peri Peri Veg",
    productDescription: "Peri Peri Sauce, veggie mix, Jalapenos, Peppadew",
    productPrice: 7400,
    productImage: PeriPeriVeg,
  },
  {
    id: 16,
    productName: "Super Supreme",
    productDescription:
      "Pizza Sauce, pepperoni, Sliced macon,Beef, diced macon,veggie mix, olives, macon",
    productPrice: 8100,
    productImage: SuperSupreme,
  },
  {
    id: 17,
    productName: "Sweet Chilli Chicken",
    productDescription: "Sweet Chilli sauce, chicken",
    productPrice: 7600,
    productImage: SweetChilliChicken,
  },
  {
    id: 18,
    productName: "Tikka Chicken",
    productDescription: "Tikka sauce, chicken, Red Onion, Mushroom",
    productPrice: 7600,
    productImage: TikkaChicken,
  },
  {
    id: 19,
    productName: "Tikka Veg",
    productDescription: "Tikka Sauce, veggie mix , Jalapenos",
    productPrice: 7400,
    productImage: TikkaVeg,
  },
  {
    id: 20,
    productName: "Triple Meat Suya",
    productDescription: "Pepperoni,Suya Beef, Sliced Macon",
    productPrice: 8100,
    productImage: TripleMeatSuya,
  },
];
